# Generated by Django 2.1.11 on 2020-04-03 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=24)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('size', models.IntegerField(default=0)),
                ('url', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntryFiles', to='diary.Entry')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-date_created',),
            },
        ),
    ]
