# Generated by Django 2.1.11 on 2019-11-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20191113_2250'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.AddField(
            model_name='file',
            name='entry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='EntryFiles', to='diary.Entry'),
            preserve_default=False,
        ),
    ]
