# Generated by Django 2.1.11 on 2019-12-15 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='media_type',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 18, 42, 24, 156145, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
