# Generated by Django 2.1.11 on 2019-11-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20191113_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
