# Generated by Django 2.1.11 on 2019-12-15 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20191215_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 18, 56, 48, 11161, tzinfo=utc)),
        ),
    ]
