# Generated by Django 2.1.11 on 2019-12-15 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20191215_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 19, 10, 29, 966967, tzinfo=utc)),
        ),
    ]
