# Generated by Django 2.1.11 on 2019-12-18 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_auto_20191215_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 20, 59, 33, 887035, tzinfo=utc)),
        ),
    ]
