# Generated by Django 2.1.11 on 2019-12-19 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20191219_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 33, 0, 889164, tzinfo=utc)),
        ),
    ]
