# Generated by Django 2.1.11 on 2019-12-19 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20191219_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 37, 17, 208763, tzinfo=utc)),
        ),
    ]
