# Generated by Django 2.1.11 on 2019-12-20 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20191219_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 23, 50, 20, 362421, tzinfo=utc)),
        ),
    ]
