# Generated by Django 2.1.11 on 2019-12-28 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20191220_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 4, 33, 31, 89649, tzinfo=utc)),
        ),
    ]
