# Generated by Django 2.1.11 on 2019-12-30 00:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_auto_20191228_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 0, 29, 6, 680137, tzinfo=utc)),
        ),
    ]
