# Generated by Django 2.1.11 on 2020-01-04 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_auto_20191230_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 2, 36, 21, 235018, tzinfo=utc)),
        ),
    ]
