# Generated by Django 2.1.11 on 2020-03-15 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0015_auto_20200104_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 18, 37, 13, 278128, tzinfo=utc)),
        ),
    ]
