# Generated by Django 2.1.11 on 2020-03-15 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_auto_20200315_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 20, 34, 54, 629974, tzinfo=utc)),
        ),
    ]
