# Generated by Django 2.2.10 on 2020-06-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
