# Generated by Django 2.2.10 on 2020-04-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',), 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='entry',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people', to='diary.Person'),
        ),
    ]
