# Generated by Django 2.1.11 on 2019-11-08 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20191108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 20, 25, 26, 93438, tzinfo=utc)),
        ),
    ]
