# Generated by Django 2.1.11 on 2019-11-15 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20191113_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 22, 37, 45, 977029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
