# Generated by Django 2.1.11 on 2019-11-19 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20191115_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 9, 20, 4, 182376, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='html',
            field=models.TextField(default='<p><br></p>'),
        ),
    ]
