# Generated by Django 2.1.11 on 2019-11-04 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20191028_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_defined_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 3, 9, 41, 820170, tzinfo=utc)),
        ),
    ]
