# Generated by Django 2.2.10 on 2020-04-26 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200404_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name'),
        ),
    ]
