# Generated by Django 2.2.10 on 2020-04-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200426_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('date_updated', '-date_created_by_author'), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
