# Generated by Django 2.1.11 on 2019-11-04 03:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_entry_date_defined_by_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_defined_by_author',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 3, 12, 48, 644965, tzinfo=utc)),
        ),
    ]
