# Generated by Django 2.2.10 on 2020-05-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200429_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_updated', '-date_created_by_author'), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
