# Generated by Django 2.1.11 on 2019-11-24 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20191120_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 6, 24, 54, 826350, tzinfo=utc)),
        ),
    ]
