# Generated by Django 2.1.11 on 2019-11-24 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20191124_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='entry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 6, 52, 13, 137896, tzinfo=utc)),
        ),
    ]
