# Generated by Django 2.1.11 on 2019-11-26 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20191124_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 5, 26, 8, 644066, tzinfo=utc)),
        ),
    ]
