# Generated by Django 2.1.11 on 2019-12-18 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20191215_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 20, 59, 33, 884700, tzinfo=utc)),
        ),
    ]
