# Generated by Django 2.1.11 on 2019-12-19 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20191218_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 21, 33, 675697, tzinfo=utc)),
        ),
    ]
