# Generated by Django 2.1.11 on 2019-12-28 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20191220_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 4, 33, 31, 86201, tzinfo=utc)),
        ),
    ]
