# Generated by Django 2.1.11 on 2020-03-15 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0020_auto_20200104_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-date_created_by_author', 'date_updated'), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 18, 37, 13, 276005, tzinfo=utc)),
        ),
    ]
