# Generated by Django 2.1.11 on 2020-03-15 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_auto_20200315_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='public',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created_by_author',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 20, 34, 54, 627830, tzinfo=utc)),
        ),
    ]
