# Generated by Django 2.1.11 on 2020-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ('-date_created',),
            },
        ),
    ]
