# Generated by Django 2.1.11 on 2019-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
