# Generated by Django 2.1.11 on 2019-12-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0002_auto_20191219_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='id',
        ),
        migrations.AlterField(
            model_name='version',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
