# Generated by Django 2.1.7 on 2019-10-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcool', models.CharField(max_length=256)),
                ('degree', models.CharField(max_length=256)),
                ('field_of_study', models.CharField(max_length=256)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('location', models.CharField(max_length=256)),
                ('grade', models.FloatField()),
                ('activities_and_societies', models.TextField()),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('-end_year',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('position', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('education_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EducationMedia', to='education.Education')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'ordering': ('-date_created',),
            },
        ),
    ]
