# Generated by Django 2.1.7 on 2019-10-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SpecializationSkillExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, to='technical_skill.Skill', verbose_name='Specialization Skills')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecializationSkillExperience', to='technical_skill.Specialization')),
            ],
            options={
                'verbose_name': 'SpecializationSkillExperience',
                'verbose_name_plural': 'SpecializationSkillExperiences',
                'ordering': ('position',),
            },
        ),
    ]
