# Generated by Django 2.1.7 on 2019-10-16 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technical_skill', '0003_auto_20191014_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserSpecialization', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
