# Generated by Django 2.1.7 on 2019-10-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('position', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BulletPoint',
                'verbose_name_plural': 'BulletPoint',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.CharField(max_length=8)),
                ('end_date', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('position', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExperienceMedia', to='experience.Experience')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='experience_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BulletPoint', to='experience.Experience'),
        ),
    ]
