# Generated by Django 2.1.11 on 2019-12-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='full_container_width',
            field=models.BooleanField(default=True),
        ),
    ]
