# Generated by Django 2.1.7 on 2019-10-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_skill', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, to='technical_skill.SpecializationSkillExperience', verbose_name='Technical Skills'),
        ),
    ]
