# Generated by Django 2.1.11 on 2019-11-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_uri',
        ),
    ]
