# Generated by Django 2.2.10 on 2020-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200409_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='show_animated_background',
            field=models.BooleanField(default=True),
        ),
    ]
