# Generated by Django 2.1.7 on 2019-10-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_uri',
            field=models.SlugField(unique=True),
        ),
    ]
