# Generated by Django 2.1.11 on 2019-11-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_profile_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='offline_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setting',
            name='show_footer',
            field=models.BooleanField(default=False),
        ),
    ]
