# Generated by Django 2.1.11 on 2020-01-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191230_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='full_container_width',
        ),
    ]
