# Generated by Django 2.1.7 on 2019-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
        ('education', '0001_initial'),
        ('user', '0003_auto_20191014_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(blank=True, to='education.Education', verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.ManyToManyField(blank=True, to='experience.Experience', verbose_name='Experience'),
        ),
    ]
