# Generated by Django 2.1.11 on 2019-10-27 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialauthentication',
            name='user_id',
        ),
        migrations.AddField(
            model_name='socialauthentication',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SocialAuthentications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
